### ISSUE TITLE
GRAMMAR OF XXXX を日本語にした方が良いか？

### ISSUE THREAD

**Issue by stzn** [stzn/the-swift-programming-language-jp#168]
他の言語の翻訳版でも英語のままだったのでそうしているが、日本語にした方が良いか？

**Comment by tsubasakat** [comment]
英語わからない方が読んでも学習の障害になるほどではないと思うので、自分はそのままにする立場に 1 票 😃

**Comment by stzn** [comment]
僕もそのままで良いと思っていたので、このチケットはクローズします。
