### ISSUE TITLE
誤植の報告：コレクション型 - 辞書

### ISSUE THREAD

**Issue by nukopy** [stzn/the-swift-programming-language-jp#227]
PR 送る余裕が無くて申し訳ないのですが、誤植を見つけたので報告します。
「コレクション型 - 辞書 - 辞書の繰り返し処理」の節にて、「配列の繰り返し処理」に出てきた内容がそのままコピペされたものが記述されていました。以下、該当箇所のリンク、スクショです。

- [該当箇所のリンク](https://www.swiftlangjp.com/language-guide/collection-types.html#%E8%BE%9E%E6%9B%B8%E3%81%AE%E7%B9%B0%E3%82%8A%E8%BF%94%E3%81%97%E5%87%A6%E7%90%86iterating-over-a-dictionary)

スクショ↓

![image](https://user-images.githubusercontent.com/42367320/140167581-2558afea-3bd7-47ec-9a87-34f3aa712b2b.png)

**Comment by stzn** [comment]
@nukopy さん
ありがとうございます！修正しました。
