### ISSUE TITLE
Regular Expression Literals

### ISSUE THREAD

**Issue by stzn** [stzn/the-swift-programming-language-jp#245]
https://docs.swift.org/swift-book/ReferenceManual/LexicalStructure.html#ID650

**Comment by KS1019** [comment]
翻訳やります。（自分ではアサイン出来なさそうなので、アサインしていただければ助かります！）

**Comment by stzn** [comment]
ありがとうございます👏🏻

>（自分ではアサイン出来なさそうなので、アサインしていただければ助かります！）

知りませんでしたw調べてみます。ありがとうございます！
