### ISSUE TITLE
改訂履歴更新

### ISSUE THREAD

**Issue by stzn** [stzn/the-swift-programming-language-jp#248]
https://docs.swift.org/swift-book/RevisionHistory/RevisionHistory.html

**Comment by jollyjoester** [comment]
@stzn やりまっす💪

**Comment by stzn** [comment]
@jollyjoester
こちら進捗いかがでしょうか？お忙しければ引き取ります！

**Comment by jollyjoester** [comment]
@stzn うわすみません！失念していました🙏この土日目処に実施させてください！
