### ISSUE TITLE
変換辞書の作成

### ISSUE THREAD

**Issue by stzn** [stzn/the-swift-programming-language-jp#249]
同じ単語は同じ翻訳をしたい。他の翻訳ページを見ると、READMEに載せるのが良さそう。

**Comment by tsubasarc** [comment]
こういう感じのやつですか？

|原語|訳語|参考|
|----|----|----|
|binary|二項, 2 進|✅二項演算子 ❌バイナリ|
|prefix|前置|✅前置演算子 ❌プレフィックス|
|infix|中置|✅中置演算子 ❌インフィックス|
|suffix|後置|✅後置演算子 ❌サフィックス|

**Comment by stzn** [comment]
@tsubasarc

はい、そんな感じです。

章をまたがって共通で使いそうなものの一覧ですかねー。特に人によって訳し方が変わりそうな部分を統一したいというのが目的です。
例えば、struct(構造体)、enum(列挙型)、function(関数)、method(メソッド)など

一旦現状使っている単語の一覧を作成してみて、「ここ変えた方が良いのでは？」というところがあれば一括で変えていきたいなとも思ってます。

**Comment by tsubasarc** [comment]
どんな単語が使われているのかまとめる為に、形だけ表を足してみました。
自分は並び順とかけっこう悩みそうです…。

**Comment by stzn** [comment]
@tsubasarc 
ありがとうございます！訳を統一をしたいので参考の列はいらないかなーと思いました(せっかく作っていただいて恐縮ですが...)

> 自分は並び順とかけっこう悩みそうです…。

並び順は表の並び順ですか？アルファベット順で良いのかなという気がします！

**Comment by tsubasarc** [comment]
@stzn 
> 訳を統一をしたいので参考の列はいらないかなーと思いました(せっかく作っていただいて恐縮ですが...)

そうですよねー 😅 

やっぱりアルファベット順が楽ですね。
