### ISSUE TITLE
表記ゆれの修正(プレフィックス->前置など)

### ISSUE THREAD

**Issue by stzn** [stzn/the-swift-programming-language-jp#292]
(僕が最初に紛れさせてしまっていた)下記の単語の表記ゆれを修正したい。

プレフィックス->前置
サフィックス->後置
バイナリ->二項

**Comment by tsubasakat** [comment]
[Advanced Operators](https://github.com/stzn/the-swift-programming-language-jp/blob/360f2e8dafc666145bbcffab62cdfd95d2f57969/language-guide/advanced-operators.md) で同じような表記揺れを見つけました。
