### ISSUE TITLE
[Advanced Operators] 読みやすさを向上させたい

### ISSUE THREAD

**Issue by tsubasarc** [stzn/the-swift-programming-language-jp#301]
この Issue では [ビット演算子](https://github.com/stzn/the-swift-programming-language-jp/blob/8968d3bb68043bc282190dd3c27203efad7f2028/language-guide/advanced-operators.md?plain=1#L14-L164) の範囲を扱います 🙂

**Comment by tsubasarc** [comment]
@tsubasarc
混乱しないよう気をつけなさい。

- ビット数 = 8bit, 16bit, 32bit といったビットの桁
- ビット値 = 0b10001100 といったビットの数字そのもの
- 表現の数 = あるビット数で表すことができる場合の数

**Comment by tsubasarc** [comment]
@tsubasarc 保持とか格納とかどっち…😭

**Comment by stzn** [comment]
あーstoredという単語の訳がぶれているんですね😅
stored propertyという単語は「格納プロパティ」に統一したはずですが、確かにここはすごい悩んだ記憶があり他はその時々でぶれてしまった気がしています。ちょっと僕の方でも見てみますmm

**Comment by tsubasarc** [comment]
そうなんです、悩みますね 😭 
ありがとうございます 🙇

**Comment by tsubasarc** [comment]
わかりましたー！

**Comment by tsubasarc** [comment]
さすがにこれは扱う範囲を広く取りすぎてしまっているので、
一度このへんで PR しようと思います。

Overflow Operators 以下はもっと小分けに Issue します… 💦
