### ISSUE TITLE
CONTRIBUTION.mdにバックティックをつける場合の記載を追加する

### ISSUE THREAD

**Issue by stzn** [stzn/the-swift-programming-language-jp#312]
原文でspanを使って強調されていた部分にバックティックを使っている。他の言語の翻訳も同様でそれに合わせている。

という旨を記載する。

https://github.com/stzn/the-swift-programming-language-jp/pull/309#discussion_r924921304

**Comment by tsubasarc** [comment]
これは公開されている HTML を基準にして、作業する Markdown ではバックティックを使うという意味であってますか？

**Comment by stzn** [comment]
はい、おっしゃる通りです！

**Comment by tsubasarc** [comment]
試しに書いてみたんですが、こんな感じでどうでしょうか…？

**Comment by stzn** [comment]
おーありがとうございます！すごい良いと思います👏🏻

**Comment by tsubasarc** [comment]
ありがとうございます 😊
それじゃあ、PR しますね！
