### ISSUE TITLE
用語サブスクリプトの使用

### ISSUE THREAD

**Issue by t-ae** [stzn/the-swift-programming-language-jp#319]
subscript が英和対応表に書かれていません。
サブスクリプトという語彙は以下のドキュメントで決まっていますが、他の文書で使用されているのは subscript がほとんどのようです。
https://github.com/stzn/the-swift-programming-language-jp/blob/master/language-guide/subscripts.md

`定数、変数、プロパティ、または subscript` のようになっている文章が多く、サブスクリプトにしたほうが読みやすいかと思います。

**Comment by stzn** [comment]
ありがとうございます！良いと思います🙆🏻‍♂️
