### ISSUE TITLE
[Collection Types] 開発ガイドに準ずる

### ISSUE THREAD

**Issue by tsubasarc** [stzn/the-swift-programming-language-jp#322]
[Collection Types](https://github.com/stzn/the-swift-programming-language-jp/blob/777b7d6f03b85e6de0000d0226c133f2b870d0c2/language-guide/collection-types.md)
このページで開発ガイドの規則が守られていない箇所を直していきます。

例: 表記揺れがありました
https://github.com/stzn/the-swift-programming-language-jp/blob/777b7d6f03b85e6de0000d0226c133f2b870d0c2/language-guide/collection-types.md?plain=1#L10
`value` の訳が `値` ではなく `バリュー` となってしまっています。

GitHub の Projects 機能で管理してもいいのではないでしょうか。

**Comment by tsubasarc** [comment]
やってくぞ 😤

**Comment by stzn** [comment]
ありがとうございます！

この部分に関しては、配列、セットにもかかっているので「値」で良いと思います。

考えどころなのは、辞書の場合「キーバリュー」という組み合わせで使っているため、「値」ではなく「バリュー」という表現が適している箇所があるのかなと思っています。(ここも他の方のご意見をお伺いしたいところです。)

> GitHub の Projects 機能で管理してもいいのではないでしょうか。

こういう機能がベータであるんですね💡時間のある時に調べてみますmm

**Comment by tsubasarc** [comment]
辞書だけに触れている時の `value` は文脈による可能性ということですね。
`要素` という語も浮かびましたが、適切なのか分かりません…。

とりあえず `value` の表記揺れは他の方の意見を待ち、
それ以外の部分をチェックしていきます 😃

**Comment by tsubasarc** [comment]
@stzn さんに確認です！

以前にも話に上がった store については、ドキュメント全体における統一という意味なのでしょうか。
https://github.com/stzn/the-swift-programming-language-jp/issues/301#issuecomment-1185332858

**Comment by t-ae** [comment]
キーバリューペアという語は定義があるので、`key-value pair` についてはキーバリューペアでいいと思います。
https://github.com/stzn/the-swift-programming-language-jp/blob/777b7d6f03b85e6de0000d0226c133f2b870d0c2/language-guide/collection-types.md?plain=1#L474

これを根拠として、辞書型ではバリューを使っていくというのでも良いんじゃないでしょうか。

**Comment by stzn** [comment]
すいません、言い方が回りくどくてわかりずらいですね💦

@t-ae さんのおっしゃる通り「キーバリューペア」という決まった言い回しがあるので、辞書の場合はバリューを使った方が良いと思っています。

storeに関しては、決まった言い回しがないのですがわかりやすさという点で「格納」に統一した方が良いという話になりました。

**Comment by tsubasarc** [comment]
> @t-ae さんのおっしゃる通り「キーバリューペア」という決まった言い回しがあるので、辞書の場合はバリューを使った方が良いと思っています。

分かりました、辞書の `value` については `バリュー` の訳になるよう気をつけます！

> storeに関しては、決まった言い回しがないのですがわかりやすさという点で Stored propertyを「格納プロパティ」としているところから「格納」に統一した方が良いという話になりました。

ではここでも `格納` にして問題なさそうなところはそのようにしていきますね。

**Comment by tsubasarc** [comment]
この Issue は Close します。

とても質が良かったので `subscript syntax` だけ翻訳していたのですが、
@t-ae さんによる先の PR で包括的に解消済み 🎉
