### ISSUE TITLE
キーパスの翻訳の統一

### ISSUE THREAD

**Issue by t-ae** [stzn/the-swift-programming-language-jp#325]
現状では`キーパス`、`KeyPath`、`key-path`、`key path`が混在しています。
原文では型を指す `KeyPath` 以外では `key path` か`key-path`  が使われています。

関連して、`identity key path`(\.self)の翻訳が`識別キーパス`となっていますが、識別だと意味が違うような気がします。

**Comment by stzn** [comment]
ありがとうございます。型はKeyPathで良いかなと思いました。残りは日本語訳が見つからなければ`key path`が良いかなと思いますが、いかがでしょうか？

> 関連して、identity key path(.self)の翻訳が識別キーパスとなっていますが、識別だと意味が違うような気がします。

変ですね。`self key path`で良いような気がしますねー。いかがでしょうか？

**Comment by t-ae** [comment]
以下の18:44から `SE-0249 Key Path Expressions as Functions` の話ですが、字幕では全体に `KeyPath` ですね。
https://developer.apple.com/videos/play/wwdc2020/10170
型の `KeyPath` と混在してしまうという問題がありますが…

> 変ですね。self key pathで良いような気がしますねー。いかがでしょうか？

下手に `自己参照KeyPath` みたいにするより `self KeyPath` のほうがシンプルで良さそうですね。

**Comment by stzn** [comment]
> 字幕では全体に KeyPath ですね。型の KeyPath と混在してしまうという問題がありますが…

そうですねえ...ひとまず公式に合わせて、もしわかりづらいなどの意見が出てきたら検討し直すが良いかなと思います！
