### ISSUE TITLE
identity Operator の翻訳

### ISSUE THREAD

**Issue by t-ae** [stzn/the-swift-programming-language-jp#336]
https://github.com/stzn/the-swift-programming-language-jp/blob/8491d98b859944cf26f987485c9d806ec07be35e/language-guide/structures-and-classes.md#%E6%81%92%E7%AD%89%E4%BD%9C%E7%94%A8%E7%B4%A0identity-operators

 `identity operator` の翻訳として`恒等作用素`が使われていますが、これは恒等写像の同義語のようです。
https://ja.wikipedia.org/wiki/%E6%81%92%E7%AD%89%E5%86%99%E5%83%8F
`===` や `!==` は恒等写像とは異なる演算子なので、別の翻訳を考えるべきかと思います。

**Comment by stzn** [comment]
ご指摘ありがとうございます！ここら辺あまりわかっていなかったのでとても助かりますmm

**Comment by jollyjoester** [comment]
この文脈だと `xxx演算子` と訳すのが良さそうですね。

候補は下記がありそうですが、どれもググって正式に使われているシーンがちゃんと見つけられないです・・・
- アイデンティティ演算子
- 恒等演算子
- 同値演算子

JaveScriptでは下記の日本語がよくヒットするようです。
- 等値演算子(Equality operator)
- 同値演算子(Identity operator)

c.f.
https://so-zou.jp/web-app/tech/programming/javascript/grammar/operator/equality-identity.htm

**Comment by stzn** [comment]
すいません。だいぶ昔の話になってしまったのですが...w

ここは「同値演算子」でいきたいと思います。もしご意見ございましたら教えてくださいmm
