### ISSUE TITLE
文中の「〜である〜」の使用

### ISSUE THREAD

**Issue by t-ae** [stzn/the-swift-programming-language-jp#346]
https://github.com/stzn/the-swift-programming-language-jp/pull/326#discussion_r931985009
ここで書きましたが、`〜である〜`と書きたい所を`〜な〜`と書いている箇所が散見されます。

[textlint-rule-no-mix-dearu-desumasuのREADME](https://github.com/textlint-ja/textlint-rule-no-mix-dearu-desumasu/blob/master/README.md#options)によると、オプションで`strict: false`と設定することで文中の`〜である〜`が弾かれなくなるようです。
問題なさそうならこの設定に変えても良いのではないでしょうか。

**Comment by stzn** [comment]
> 箇所が散見されます。

こちらはtextlintのエラーが出ているということでしょうか？

全然変更大丈夫です。煩わしい設定をしていてごめんなさい。
