### ISSUE TITLE
Swiftツアー(A Swift Tour) にリンク切れがある

### ISSUE THREAD

**Issue by elmetal** [stzn/the-swift-programming-language-jp#418]
冒頭のNoteにある以下のファイルへのリンクが404になっています。
> https://docs.swift.org/swift-book/GuidedTour/GuidedTour.playground.zip

Noteの項目は原文には存在しないのでどういう対応をすべきかわからないのですが、削除してしまってもいいのでは？と思っています。
適切な対応に誘導してもらえれば私が対応します。

**Comment by stzn** [comment]
ありがとうございます！原文から消えていたことに気がついていませんでしたmm

おっしゃる通り、NOTEの部分を丸ごと削除していただけるとうれしいですmm

> NOTE  
> より理解を深めるために、Xcode でこのチャプターを開いて遊んでみましょう。Playgrounds を使用すると、コードを編集して結果をすぐに確認することができます。
>
> [Download Playground](https://docs.swift.org/swift-book/GuidedTour/GuidedTour.playground.zip)
