### ISSUE TITLE
Concurrencyの改善

### ISSUE THREAD

**Issue by stzn** [stzn/the-swift-programming-language-jp#443]
https://github.com/apple/swift-book/pull/159

**Comment by KaitoMuraoka** [comment]
@stzn

**Comment by stzn** [comment]
@KaitoMuraoka さん

お疲れ様です！

こちらですが、もう始められていますでしょうか？

もしまだでしたら僕の方でやろうと思っています🙂

**Comment by KaitoMuraoka** [comment]
@stzn 
すみません。対応がもう少しかかりそうなので、Assignees を外していただいても構いません。 🙇 
ご迷惑をおかけして、申し訳ないです 🙇

**Comment by stzn** [comment]
いえいえー。そうしましたら一旦僕の方で引き取りますね！
ありがとうございます！
