### ISSUE TITLE
borrowingとconsumingパラメータの追加

### ISSUE THREAD

**Issue by stzn** [stzn/the-swift-programming-language-jp#446]
https://github.com/apple/swift-book/pull/173

**Comment by NiwakaDev** [comment]
急ぎでなければ、このissueを引き受けたいです。(誰もこのissueを引き受けていなければ。)

**Comment by stzn** [comment]
ありがとうございます！よろしくお願いします!
作業を始める際はまずアサインすることになっているので、されていなければ大丈夫です🙆

**Comment by stzn** [comment]
@NiwakaDev さん

お疲れ様です！

こちらですが、もう始められていますでしょうか？
もしまだでしたら僕の方でやろうと思っています🙂
