### ISSUE TITLE
[制御フロー(Control Flow)]ドキュメント参照の確認と修正

### ISSUE THREAD

**Issue by TonTonbow** [stzn/the-swift-programming-language-jp#456]
## 問題の箇所
以下の場所で参照箇所の表記にズレがありました。何か意図があってこの表記にしているのであれば、解説をいただきたいです。

https://github.com/stzn/the-swift-programming-language-jp/blob/2b4d9ee290352719e00682fe70807e04bcef7000/language-guide/control-flow.md?plain=1#L341

<img width="787" alt="スクリーンショット 2023-08-27 11 07 09" src="https://github.com/stzn/the-swift-programming-language-jp/assets/70003919/67ad1a66-fdd7-49eb-9238-b288874d2038">

[問題ページ](https://www.swiftlangjp.com/language-guide/control-flow.html#if)

## 修正案
以下のような表記が良いと考えます。

```diff markdown
- doc:TheBasics#Type-Annotations [型注釈\(Type Annotations\)](../language-guide/the-basics.md#type-annotations)
+ [型注釈\(Type Annotations\)](../language-guide/the-basics.md#type-annotations)
```

**Comment by stzn** [comment]
@TonTonbow さん

ご指摘ありがとうございます。

> 何か意図があってこの表記にしているのであれば、解説をいただきたいです。

ただの間違いです。DocC対応を試している際に混入してしまったようです。大変申し訳ございませんmm
修正案の通りでよいと思います。

**Comment by TonTonbow** [comment]
@stzn 
ありがとうございます！
では自分がそのまま修正します 🙋

**Comment by stzn** [comment]
ありがとうございます！
