### ISSUE TITLE
サイト全体のレスポンシブ対応

### ISSUE THREAD

**Issue by tez3998** [stzn/the-swift-programming-language-jp#476]
素晴らしいドキュメントをありがとうございます。

サイト全体をレスポンシブ対応していただけないかと思い、Issueを立てました。
閲覧する端末がスマホの場合、文章が画面の外まで伸びでしまっているため、常に画面を左右にスライドされなければならず、読みづらさがあります。

**Comment by stzn** [comment]
ご連絡ありがとうございます。

[honkit](https://github.com/honkit/honkit)というフレームワークを使っているのですが、そこでどう対応できるか調べてみます(もしくはどなたか調べていただける方がいれば嬉しいです。)

すぐには対応できないと思いますのでお待ちいただけましたら幸いですmm

よろしくお願いします。

**Comment by tez3998** [comment]
@stzn 
私をAssigneesにしていただけますでしょうか。

**Comment by stzn** [comment]
@tez3998 san

ありがとうございます！見ていただけると助かります🙇🏻‍♂️
