### ISSUE TITLE
誤字脱字、フォーマットの見直し

### ISSUE THREAD

**Issue by stzn** [stzn/the-swift-programming-language-jp#52]

**Comment by ensan-hcl** [comment]
#100 のPRでいくつか修正したのですが、開きが全角かっこ、閉じが半角かっこになっている部分がかなりありました。全角と半角の使い分けには何か決まりがありますか？

**Comment by stzn** [comment]
> 開きが全角かっこ、閉じが半角かっこ

全部半角かっこが正しいので全角かっこは間違いです!

**Comment by ensan-hcl** [comment]
なるほど、中途半端に直してしまったのはむしろマズかったかもしれません🙏

**Comment by stzn** [comment]
いえいえ、ホントすごい助かってます🙏🏻

**Comment by stzn** [comment]
ひとまず1周したのでCloseします。また見つけたらissueを新しく立てます。
